version: "1"
label: ":alien:"
rules:
  - base: master
    upstream: "odoo:master"
    mergeMethod: merge
  - base: "17.0"
    upstream: "odoo:17.0"
    mergeMethod: merge
  - base: "16.0"
    upstream: "odoo:16.0"
    mergeMethod: merge
